summarize_tree: summarize_tree.c
	gcc -Wall -Wpedantic -g -o summarize_tree summarize_tree.c

summarize_tree_ftw: summarize_tree_ftw.c
	gcc -Wall -Wpedantic -g -o summarize_tree_ftw summarize_tree_ftw.c

clean:
	rm summarize_tree
	rm summarize_tree_ftw